workspace:
  base: /go
  path: src/github.com/drone/drone-cli

pipeline:
  test:
    image: golang:1.8
    commands:
      - echo starting
      - cd drone
      - go test

  build:
    image: golang:1.8
    commands: sh .drone.sh

  publish:
    image: plugins/github-release
    files:
      - release/drone_*.tar.gz
      - release/drone_checksums.txt
    secrets:
      - source: github_token
        target: github_release_api_key
    when:
      event: tag

  docker_publish:
    image: plugins/docker
    repo: drone/drone-cli
    secrets: [ docker_username, docker_password ]
    tag: [ latest ]
    when:
      event: tag
