workspace:
  base: /go
  path: src/github.com/drone/drone-cli

pipeline:
  test:
    image: golang:1.8
    commands:
      - echo starting
      - cd drone
      - go test

  build:
    image: golang:1.8
    commands: sh .drone.sh

  publish:
    image: plugins/github-release
    files:
      - release/drone_*.tar.gz
      - release/drone_checksums.txt
    secrets:
      - source: github_token
        target: github_release_api_key
    when:
      event: tag

 publish_latest:
    image: plugins/docker
    repo: ${DRONE_REPO}
    tags: [ 'latest' ]
    secrets: [ docker_username, docker_password ]
    when:
      event: [ push ]
      branch: [ master ]

  publish_tag:
    image: plugins/docker
    repo: ${DRONE_REPO}
    tags: [ '${DRONE_TAG}' ]
    secrets: [ docker_username, docker_password ]
    group: release
    when:
      event: [ tag ]
      branch: [ refs/tags/* ]
